import { NetworkCase } from 'src/@types/case';
import axiosInstance from 'src/utils/axios';

const VICTIM_DATA_MOCK: Partial<NetworkCase>[] = [
  {
    id: 40,
    description: 'Test',
    consent: false,
    createdAt: '2023-02-19T19:17:47.811Z',
    code: 'C9827',
    completed: false,
    inactive: false,
    jurisdiction: '',
    defendant: 'Oscar Maldonado',
    defendantId: '',
    proceduralStage: '',
    legalScore: '',
    victim: {
      id: 123456789,
      name: 'Mariana Orozco',
      email: ' marianaorozco@gmail.com',
      otherName: '',
      age: 25,
      verifiedAge: 25,
      birthday: '1997-10-23',
      citizenship: 'Dominicana',
      ethnicity: 'Latina',
      nationality: 'República Dominicana',
      maritalStatus: 4,
      children: 2,
      originAddress: '52AVE 8-90 Barrio La Merced',
      currentAddress: '52AVE 8-90 Barrio La Merced',
      phoneNumber: '56789812',
      preferredLanguage: 'Español',
      genre: 0,
    },
    provider: {
      id: 1,
      name: 'RELEVIC',
      phoneNumber: '54678901',
      email: 'test@test.com',
      address: 'test',
      description: 'test',
      networkInterest: 1,
      networkNeeds: [1, 2, 3],
      provinceId: 1,
      serviceTypeId: 1,
      providerAreaId: 1,
    },
    userInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    consentUserInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    demographicForm: {
      id: 33,
      completed: false,
      caseId: 1,
      participation: '',
      commitment: 0,
      comments: '',
      description: '',
      createdAt: '2023-02-19T19:17:47.754Z',
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        status: '',
        roleId: 1,
      },
    },
    initialSurvivorEvaluation: {
      caseId: 2,
      id: 97,
      violenceType: 0,
      place: '',
      phase: 0,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.771Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    finalSurvivorEvaluation: {
      caseId: 1,
      id: 98,
      violenceType: 0,
      place: '',
      phase: 1,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.785Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    postSurvivorEvaluation: {
      caseId: 1,
      id: 99,
      violenceType: 0,
      place: '',
      phase: 2,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.794Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    attentionProtocol: {
      caseId: 1,
      id: 33,
      data: '',
      confidentiality: false,
      consent: false,
      treatment: false,
      security: '[]',
      legalProtection: '[]',
      mental: '[]',
      financial: '[]',
      social: '[]',
      physical: '[]',
      strengths: '',
      comments: '',
      completed: false,
      createdAt: '2023-02-19T19:17:47.802Z',
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        status: '',
        roleId: 1,
      },
    },
    followUpUserInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    followUpNotes: [],
    comments: [],
    followUps: [],
  },
  {
    description: 'Test without id',
    consent: false,
    createdAt: '2023-02-19T19:17:47.811Z',
    code: 'C9822',
    completed: false,
    inactive: false,
    jurisdiction: '',
    defendant: 'Oscar Maldonado',
    defendantId: '',
    proceduralStage: '',
    legalScore: '',
    victim: {
      id: 123456789,
      name: 'Mariana Orozco',
      email: ' marianaorozco@gmail.com',
      otherName: '',
      age: 25,
      verifiedAge: 25,
      birthday: '1997-10-23',
      citizenship: 'Dominicana',
      ethnicity: 'Latina',
      nationality: 'República Dominicana',
      maritalStatus: 4,
      children: 2,
      originAddress: '52AVE 8-90 Barrio La Merced',
      currentAddress: '52AVE 8-90 Barrio La Merced',
      phoneNumber: '56789812',
      preferredLanguage: 'Español',
      genre: 0,
    },
    provider: {
      id: 1,
      name: 'RELEVIC',
      phoneNumber: '54678901',
      email: 'test@test.com',
      address: 'test',
      description: 'test',
      networkInterest: 1,
      networkNeeds: [1, 2, 3],
      provinceId: 1,
      serviceTypeId: 1,
      providerAreaId: 1,
    },
    userInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    consentUserInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    demographicForm: {
      id: 33,
      completed: false,
      caseId: 1,
      participation: '',
      commitment: 0,
      comments: '',
      description: '',
      createdAt: '2023-02-19T19:17:47.754Z',
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        status: '',
        roleId: 1,
      },
    },
    initialSurvivorEvaluation: {
      caseId: 2,
      id: 97,
      violenceType: 0,
      place: '',
      phase: 0,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.771Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    finalSurvivorEvaluation: {
      caseId: 1,
      id: 98,
      violenceType: 0,
      place: '',
      phase: 1,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.785Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    postSurvivorEvaluation: {
      caseId: 1,
      id: 99,
      violenceType: 0,
      place: '',
      phase: 2,
      security1: 1,
      security2: 1,
      security3: 1,
      securityNotes: '',
      legalProtection1: 1,
      legalProtection2: 1,
      legalProtection3: 1,
      legalProtectionNotes: '',
      mentalWelfare1: 1,
      mentalWelfare2: 1,
      mentalWelfare3: 1,
      mentalWelfare4: 1,
      mentalWelfareNotes: '',
      financial1: 1,
      financial2: 1,
      financial3: 1,
      financial4: 1,
      financialNotes: '',
      social1: 1,
      social2: 1,
      social3: 1,
      social4: 1,
      socialNotes: '',
      physical1: 1,
      physical2: 1,
      physical3: 1,
      physical4: 1,
      physical5: 1,
      physicalNotes: '',
      total: 0,
      survivorStatus: 0,
      createdAt: '2023-02-19T19:17:47.794Z',
      completedAt: '',
      completed: false,
      securityTotal: 1,
      legalProtectionTotal: 1,
      mentalWelfareTotal: 1,
      financial: 1,
      social: 1,
      physical: 1,
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        provider: {
          id: 1,
          name: 'RELEVIC',
          phoneNumber: '54678901',
          email: 'test@test.com',
          address: 'test',
          description: 'test',
          networkInterest: 1,
          networkNeeds: [1, 2, 3],
          provinceId: 1,
          serviceTypeId: 1,
          providerAreaId: 1,
        },
        status: '',
        roleId: 1,
        role: {
          description: '',
          id: 1,
          name: '',
          permissions: [],
        },
      },
    },
    attentionProtocol: {
      caseId: 1,
      id: 33,
      data: '',
      confidentiality: false,
      consent: false,
      treatment: false,
      security: '[]',
      legalProtection: '[]',
      mental: '[]',
      financial: '[]',
      social: '[]',
      physical: '[]',
      strengths: '',
      comments: '',
      completed: false,
      createdAt: '2023-02-19T19:17:47.802Z',
      userInCharge: {
        id: 25,
        email: 'emilio@relevic.com',
        name: 'Emilio Barrientos',
        status: '',
        roleId: 1,
      },
    },
    followUpUserInCharge: {
      id: 25,
      email: 'emilio@relevic.com',
      name: 'Emilio Barrientos',
      status: '',
      roleId: 1,
    },
    followUpNotes: [],
    comments: [],
    followUps: [],
  },
];

export default class CaseService {
  static searchCaseByCode = async (code: string) =>
    // TODO: Replace with the correct path
    // const { data } = await axiosInstance.get<NetworkCase>(`/path-to-search/code/${code}`);
    VICTIM_DATA_MOCK[1];

  static searchCaseByVictim = async (id: string) =>
    // TODO: Replace with the correct path
    // const { data = [] } = await axiosInstance.get<NetworkCase[]>(`/path-to-search/victim/${id}`);
    VICTIM_DATA_MOCK;
}
