export const PROVIDERS_MOCK = [
  {
    id: 1,
    name: 'Proveedor de Servicios 1',
    email: 'servicios1@proveedor.com',
    phone: '+502 22465879',
    isActive: true,
    type: 2,
    address: '',
    areaId: 1,
    description: '',
    interest: 1,
    items: [1],
    latitude: '',
    longitude: '',
    province: '',
    serviceTypeId: 2,
  },
  {
    id: 2,
    name: 'Proveedor de Servicios 2',
    email: 'servicios2@proveedor.com',
    phone: '+502 22465878',
    isActive: false,
    type: 2,address: '',
    areaId: 1,
    description: '',
    interest: 1,
    items: [1],
    latitude: '',
    longitude: '',
    province: '',
    serviceTypeId: 2,
  }
];